theme: Hacker
title: Class Management System
description: Dewasa ini, mahasiswa memiliki berbagai tanggung jawab mulai dari berbagai kelas yang berbeda, tugas kuliah, serta kegiatan berorganisasi. Variasi kegiatan mahasiswa ini membuat mahasiswa rentan mengalami kelalaian dalam mengingat dan mengorganisir kegiatan yang mereka ikuti. Aplikasi ini hadir untuk mempermudah mahasiswa mengorganisir jadwal mereka serta memberi notifikasi atas kegiatan yang akan datang.
